import 'package:equatable/equatable.dart';

import 'gigi_model.dart';

class AssetsGigiModel extends Equatable {
  final String imgAssets;
  final GigiKategori kategori;
  const AssetsGigiModel({
    required this.imgAssets,
    required this.kategori,
  });
  @override
  List<Object?> get props => [imgAssets, kategori];
}

List<AssetsGigiModel> listAssestGigiModel = [
  const AssetsGigiModel(imgAssets: "01", kategori: GigiKategori.geraham),
  const AssetsGigiModel(imgAssets: "02", kategori: GigiKategori.geraham),
  const AssetsGigiModel(imgAssets: "03", kategori: GigiKategori.geraham),
  const AssetsGigiModel(imgAssets: "04", kategori: GigiKategori.geraham),
  const AssetsGigiModel(imgAssets: "05", kategori: GigiKategori.geraham),
  const AssetsGigiModel(imgAssets: "06", kategori: GigiKategori.geraham),
  const AssetsGigiModel(imgAssets: "07", kategori: GigiKategori.geraham),
  const AssetsGigiModel(imgAssets: "08", kategori: GigiKategori.geraham),
  const AssetsGigiModel(imgAssets: "09", kategori: GigiKategori.geraham),
  const AssetsGigiModel(imgAssets: "10", kategori: GigiKategori.geraham),
  const AssetsGigiModel(imgAssets: "11", kategori: GigiKategori.geraham),
  const AssetsGigiModel(imgAssets: "12", kategori: GigiKategori.geraham),
  const AssetsGigiModel(imgAssets: "13", kategori: GigiKategori.geraham),
  const AssetsGigiModel(imgAssets: "14", kategori: GigiKategori.geraham),
  const AssetsGigiModel(imgAssets: "15", kategori: GigiKategori.geraham),
  const AssetsGigiModel(imgAssets: "16", kategori: GigiKategori.geraham),
  const AssetsGigiModel(imgAssets: "17", kategori: GigiKategori.geraham),
  const AssetsGigiModel(imgAssets: "18", kategori: GigiKategori.geraham),
  const AssetsGigiModel(imgAssets: "19", kategori: GigiKategori.geraham),
  const AssetsGigiModel(imgAssets: "20", kategori: GigiKategori.geraham),
  const AssetsGigiModel(imgAssets: "21", kategori: GigiKategori.seri),
  const AssetsGigiModel(imgAssets: "22", kategori: GigiKategori.seri),
  const AssetsGigiModel(imgAssets: "23", kategori: GigiKategori.seri),
  const AssetsGigiModel(imgAssets: "24", kategori: GigiKategori.seri),
  const AssetsGigiModel(imgAssets: "25", kategori: GigiKategori.seri),
  const AssetsGigiModel(imgAssets: "26", kategori: GigiKategori.seri),
  const AssetsGigiModel(imgAssets: "27", kategori: GigiKategori.seri),
  const AssetsGigiModel(imgAssets: "28", kategori: GigiKategori.seri),
  const AssetsGigiModel(imgAssets: "29", kategori: GigiKategori.seri),
  const AssetsGigiModel(imgAssets: "31", kategori: GigiKategori.seri),
  const AssetsGigiModel(imgAssets: "32", kategori: GigiKategori.geraham),
  const AssetsGigiModel(imgAssets: "33", kategori: GigiKategori.geraham),
  const AssetsGigiModel(imgAssets: "34", kategori: GigiKategori.geraham),
  const AssetsGigiModel(imgAssets: "35", kategori: GigiKategori.geraham),
  const AssetsGigiModel(imgAssets: "36", kategori: GigiKategori.geraham),
  const AssetsGigiModel(imgAssets: "37", kategori: GigiKategori.geraham),
  const AssetsGigiModel(imgAssets: "38", kategori: GigiKategori.geraham),
  const AssetsGigiModel(imgAssets: "39", kategori: GigiKategori.seri),
  const AssetsGigiModel(imgAssets: "40", kategori: GigiKategori.geraham),
  const AssetsGigiModel(imgAssets: "41", kategori: GigiKategori.geraham),
  const AssetsGigiModel(imgAssets: "42", kategori: GigiKategori.geraham),
  const AssetsGigiModel(imgAssets: "43", kategori: GigiKategori.geraham),
  const AssetsGigiModel(imgAssets: "44", kategori: GigiKategori.geraham),
  const AssetsGigiModel(imgAssets: "45", kategori: GigiKategori.geraham),
  const AssetsGigiModel(imgAssets: "46", kategori: GigiKategori.seri),
  const AssetsGigiModel(imgAssets: "47", kategori: GigiKategori.geraham),
  const AssetsGigiModel(imgAssets: "50", kategori: GigiKategori.seri),
  const AssetsGigiModel(imgAssets: "51", kategori: GigiKategori.seri),
  const AssetsGigiModel(imgAssets: "52", kategori: GigiKategori.seri),
  const AssetsGigiModel(imgAssets: "53", kategori: GigiKategori.seri),
  const AssetsGigiModel(imgAssets: "54", kategori: GigiKategori.seri),
  const AssetsGigiModel(imgAssets: "55", kategori: GigiKategori.seri),
  const AssetsGigiModel(imgAssets: "56", kategori: GigiKategori.seri),
  const AssetsGigiModel(imgAssets: "57", kategori: GigiKategori.seri),
  const AssetsGigiModel(imgAssets: "58", kategori: GigiKategori.seri),
  const AssetsGigiModel(imgAssets: "59", kategori: GigiKategori.seri),
  const AssetsGigiModel(imgAssets: "60", kategori: GigiKategori.seri),
  const AssetsGigiModel(imgAssets: "61", kategori: GigiKategori.seri),
  const AssetsGigiModel(imgAssets: "62", kategori: GigiKategori.seri),
  const AssetsGigiModel(imgAssets: "63", kategori: GigiKategori.seri),
  const AssetsGigiModel(imgAssets: "64", kategori: GigiKategori.seri),
  const AssetsGigiModel(imgAssets: "65", kategori: GigiKategori.seri),
  const AssetsGigiModel(imgAssets: "66", kategori: GigiKategori.seri),
  const AssetsGigiModel(imgAssets: "67", kategori: GigiKategori.seri),
  const AssetsGigiModel(imgAssets: "68", kategori: GigiKategori.seri),
  const AssetsGigiModel(imgAssets: "69", kategori: GigiKategori.seri),
  const AssetsGigiModel(imgAssets: "70", kategori: GigiKategori.seri),
  const AssetsGigiModel(imgAssets: "71", kategori: GigiKategori.seri),
  const AssetsGigiModel(imgAssets: "72", kategori: GigiKategori.seri),
  const AssetsGigiModel(imgAssets: "73", kategori: GigiKategori.seri),
];
