name: hms_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  animate_gradient: ^0.0.3
  animated_text_kit: ^4.2.2
  anydrawer: ^1.0.6
  assets_audio_player: ^3.1.1
  auto_size_text: ^3.0.0
  auto_size_text_field: ^2.2.3
  avatar_glow: ^3.0.1
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  cached_network_image: ^3.3.1
  charts_painter: ^3.1.1
  checkbox_grouped: ^2.0.0
  cupertino_icons: ^1.0.8
  custom_radio_group_list: ^1.1.2
  dartz: ^0.10.1
  data_table_2: ^2.5.12
  datetime_picker_formfield_new: ^2.1.0
  device_info_plus: ^10.1.0
  dio: ^5.4.3+1
  dropdown_button2: ^2.3.9
  easy_search_bar: ^2.5.0
  equatable: ^2.0.5
  eva_icons_flutter: ^3.1.0
  file_picker: ^8.0.3
  fl_chart: ^0.68.0
  fluent_ui: ^4.8.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_animated_button: ^2.0.3
  flutter_bloc: ^8.1.5
  flutter_bootstrap5: ^1.1.1+1
  flutter_chart: ^0.1.6
  flutter_easyloading: ^3.0.5
  flutter_form_builder: ^9.1.1
  flutter_launcher_icons: ^0.13.1
  flutter_localization: ^0.2.0
  flutter_pdfview: ^1.3.1
  flutter_screenutil: ^5.9.0
  flutter_spinbox: ^0.13.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  flutter_typeahead: ^5.2.0
  flutter_windowmanager: ^0.2.0
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.2.0
  gesture_x_detector: ^1.1.1
  get: ^4.6.6
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  graphic: ^2.2.1
  image_gallery_saver: ^2.0.3
  image_painter: ^0.7.1
  injectable: ^2.1.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  lottie: ^3.1.1
  marquee: ^2.2.3
  meta: ^1.9.1
  msix: ^3.16.7
  multi_select_flutter: ^4.1.3
  open_store: ^0.5.0
  path_provider: ^2.1.3
  pdf: ^3.10.7
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.1
  pin_code_fields: ^8.0.1
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  radio_group_v2: ^3.1.0
  roundcheckbox: ^2.0.5
  screenshot: ^3.0.0
  scrollable_positioned_list: ^0.3.8
  scrollable_table_view: ^2.0.3
  searchfield: ^1.0.1
  shared_preferences: ^2.1.0
  shimmer: ^3.0.0
  signature: ^5.4.1
  sizer: ^2.0.15
  speech_to_text: ^6.1.1
  stack_board: ^0.1.2
  syncfusion_flutter_charts: ^25.1.35
  syncfusion_flutter_core: ^25.1.35
  syncfusion_flutter_datagrid: ^25.1.35
  syncfusion_localizations: ^25.1.35
  table_desk: ^0.0.1
  universal_platform: ^1.0.0+1
  vtable: ^0.4.0
  window_manager: ^0.3.8

dev_dependencies:
  build_runner: null
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  injectable_generator: ^2.1.4
  json_serializable: ^6.6.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/images/
    - assets/images/lokalis/
    - assets/images/nyeri/
    - assets/animation/
    - assets/icons/
    - assets/svg/
    - assets/odon/
    - assets/sound/
    - assets/pdf/
    - assets/sound/ONLINE.wav

  fonts:
    - family: Calibri
      fonts:
        - asset: assets/font/calibri/Calibri-Regular.ttf
        - asset: assets/font/calibri/Calibri-Bold.ttf
        - asset: assets/font/calibri/Calibri-Italic.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/emr_logo.png"

msix_config:
  display_name: Rekam Medis Electronict
  publisher_display_name: vincentcore
  identity_name: vincentcore.co.id
  msix_version: 1.0.0.0
  logo_path: C:\HIS\app_logo_dua.png
  capabilities: internetClient, location, microphone, webcam
