// ignore_for_file: public_member_api_docs, sort_constructors_first
part of 'report_bloc.dart';

enum ReportStatus {
  initial,
  loadingReportTriase,
  loadedReportTriase,

  // Ringkasan Pulang
  loadingReportRingkasanPulang,
  loadedRingkasanPulang,

  // RAWAT INAP ANAK
  loadingReportRawatInapAnak,
  loadedReportRawwtInapAnak,
  error,

  // REPORT PERKEMBAGNAN PASIEN
  loadingPerkembanganPasien,
  loadedPerkembanganPasien,

  // CPPT REPORT
  loadingReportCPPTPasien,
  loadedReportCPPTPasien,

  isLoadingReportPengkajianRawatInap,
  loadedReportPengkajianRawatInap,

  isLoadingReportPengkajianRawatInapPerawat,
  loadedReportPengkajianRawatInapPerawat,
}

class ReportState extends Equatable {
  final ReportStatus status;
  final ReportPengkajianAwalRawatInapModel reportPengkajianAwalMedis;
  final ReportRingkasanPulangResponseModel? reportRingkasanPulang;
  final ReportPengkajianRawatInapPerawat perawat;
  final List<IntervensiPasienResponseModel> intervensiResponse;
  final List<ResponseCpptPasien> cpptPasien;
  final ReportPengkajianAwalPasienRawatInapResponseModel?
      reportRawatInapResponse;
  final ReportTriaseResponseModel reportTriase;
  const ReportState({
    required this.cpptPasien,
    required this.perawat,
    required this.status,
    required this.intervensiResponse,
    required this.reportPengkajianAwalMedis,
    required this.reportTriase,
    this.reportRawatInapResponse,
    this.reportRingkasanPulang,
  });

  static ReportState initial() => ReportState(
      perawat: ReportPengkajianRawatInapPerawat(
          riwayatPenyakit: [],
          fungsional: FungsionalModel(
              f1: "",
              f2: "",
              f3: "",
              f4: "",
              f5: "",
              f6: "",
              f7: "",
              f8: "",
              f9: "",
              f10: "",
              nilai: 0),
          asuhanKeperawatan: [],
          riwayatPengobatan: [],
          riwayatPenyakitKeluarga: [],
          nutrisiResponse: NutrisiResponse(n1: "", n2: "", nilai: 0),
          asesmenPerawat: AsesmenPerawat(
            nutrisi: "",
            perluPenerjemah: "",
            anggotaGerak: "",
            bicara: "",
            perubahanStatusMental: "",
            riwayatHipertensi: "",
            sakitKepala: "",
            akral: "",
            batuk: "",
            merokok: "",
            suaraNapas: "",
            sistemUsus: "",
            bahasaSehari: "",
            caraBelajar: "",
            eliminasiBab: "",
            eliminasiBak: "",
            hambatanBahasa: "",
            hambatanEkonomi: "",
            hambatanSosial: "",
            hambatanSpiritual: "",
            istirahat: "",
            khususKepercayaan: "",
            nilaiKepercayaan: "",
            presepsiSakit: "",
            responseEmosi: "",
            sistemAktivitas: "",
            sistemBerpakaian: "",
            sistemEliminasi: "",
            sistemHamil: "",
            sistemIntegumen: "",
            sistemKardiovaskuler: "",
            sistemKenyamaman: "",
            sistemMakan: "",
            sistemMandi: "",
            sistemMobilisasi: "",
            sistemPencernaan: "",
            sistemPendaharan: "",
            sistemPerfusiPerifer: "",
            sistemProteksi: "",
            sistemRespiratori: "",
            sistemSecebral: "",
            sitemPapsSmer: "",
            spikologis: "",
            thermoregulasi: "",
            insertDttm: "",
            jenpel: "",
            jenpelDetail: "",
            person: "",
            tglMasuk: "",
            tglKeluar: "",
            kdBagian: "",
            noreg: "",
            keluhan: "",
            userId: "",
            riwayatPenyakit: "",
            riwayatPenyakitDahulu: "",
            nama: "",
            reaksiAlergi: "",
          ),
          vital: VitalPerawat(
              insertDttm: "",
              userId: "",
              pelayanan: "",
              kdBagian: "",
              deviceId: "",
              kategori: "",
              person: "",
              noreg: "",
              td: "",
              nadi: "",
              suhu: "",
              spo2: "",
              pernafasan: "",
              tinggiBadan: "",
              beratBadan: ""),
          fisik: FisikPerawat(
              alatKelamin: "",
              anggotaGerak: "",
              refleks: "",
              otot: "",
              rtVt: "",
              gcsE: "",
              gcsM: "",
              gcsV: "",
              pupilKiri: "",
              pupilKanan: "",
              isokor: "",
              isokorDetail: "",
              anisokor: "",
              cahayaKanan: "",
              cahayaKiri: "",
              akral: "",
              pupil: "",
              kesadaran: "",
              kepala: "",
              rambut: "",
              wajah: "",
              keadaanUmum: "",
              jalanNafas: "",
              sirkulasi: "",
              gangguan: "",
              kulit: "",
              abdomen: "",
              ginjal: "",
              abdomenLainnya: "",
              peristatikUsus: "",
              thyroid: "",
              hati: "",
              paru: "",
              mata: "",
              tht: "",
              telinga: "",
              hidung: "",
              mulut: "",
              gigi: "",
              lidah: "",
              tenggorokan: "",
              lehe: "",
              lien: "",
              leherLainnya: "",
              dada: "",
              repirasi: "",
              perut: "",
              jantung: "",
              integument: "",
              ekstremitas: "",
              ekstremitasSuperior: "",
              ekstremitasInferior: "",
              kemampuanGemgam: "",
              genetalia: "",
              anus: "",
              punggung: "",
              lainLain: "",
              dindingDada: "",
              epigastrium: "",
              supratermal: "",
              retraksi: "",
              hepar: "",
              heparDetail: "",
              limpa: "",
              limpaDetail: "",
              ouf: "",
              tugorKulit: "",
              pemeriksaanFisik: "",
              skalaNyeri: 0,
              nyeriP: "",
              nyeriQ: "",
              nyeriR: "",
              nyeriS: "",
              nyeriT: "",
              flaccWajah: 0,
              flaccKaki: 0,
              flaccAktivitas: 0,
              flaccMenangis: 0,
              flaccBersuara: 0,
              flaccTotal: 0,
              skalaTriase: 0)),
      reportPengkajianAwalMedis: ReportPengkajianAwalRawatInapModel(
          diagnosa: [],
          radiologi: [],
          dPenLab: [],
          asesmenDokter: AsesmenDokter(
            diagnosaBanding: "",
            insertDttm: "",
            person: "",
            userId: "",
            pelayanan: "",
            insertPc: "",
            kdBagian: "",
            noreg: "",
            keluhUtama: "",
            rwtSekarang: "",
            tglMasuk: "",
            jamMasuk: "",
            imageLokalis: "",
            prognosis: "",
            alasanOpname: "",
            terapi: "",
            konsulke: "",
            namaDokter: "",
          ),
          vitalSignDokter: VitalSignDokter(
              insertDttm: "",
              userId: "",
              pelayanan: "",
              kdBagian: "",
              deviceId: "",
              kategori: "",
              person: "",
              noreg: "",
              td: "",
              nadi: "",
              suhu: "",
              spo2: "",
              pernafasan: "",
              tinggiBadan: "",
              beratBadan: ""),
          fisikModel: FisikModel(
              insertDttm: "",
              insertDevice: "",
              insertUserId: "",
              ketPerson: "",
              pelayanan: "",
              kdBagian: "",
              kategori: "",
              noreg: "",
              alatKelamin: "",
              anggotaGerak: "",
              refleks: "",
              otot: "",
              rtVt: "",
              gcsE: "",
              gcsM: "",
              gcsV: "",
              pupilKiri: "",
              pupilKanan: "",
              isokor: "",
              isokorDetail: "",
              anisokor: "",
              cahayaKanan: "",
              cahayaKiri: "",
              akral: "",
              pupil: "",
              kesadaran: "",
              kepala: "",
              rambut: "",
              wajah: "",
              keadaanUmum: "",
              jalanNafas: "",
              sirkulasi: "",
              gangguan: "",
              kulit: "",
              abdomen: "",
              ginjal: "",
              abdomenLainnya: "",
              peristatikUsus: "",
              thyroid: "",
              hati: "",
              paru: "",
              mata: "",
              tht: "",
              telinga: "",
              hidung: "",
              mulut: "",
              gigi: "",
              lidah: "",
              tenggorokan: "",
              leher: "",
              lien: "",
              leherLainnya: "",
              dada: "",
              respirasi: "",
              perut: "",
              jantung: "",
              integument: "",
              ekstremitas: "",
              ekstremitasSuperior: "",
              ekstremitasInferior: "",
              kemampuanGenggam: "",
              genetalia: "",
              anus: "",
              punggung: "",
              lainLain: "",
              dindingdada: "",
              dindingdadaRetEpigastrium: "",
              dindingdadaRetSuprastermal: "",
              dindingdadaRetraksi: "",
              hepar: "",
              heparDetail: "",
              limpa: "",
              limpaDetail: "",
              ouf: "",
              tugorKulit: "",
              pemeriksaanFisik: "",
              skalaNyeri: 0,
              skalaNyeriP: "",
              skalaNyeriQ: "",
              skalaNyeriR: "",
              skalaNyeriS: "",
              skalaNyeriT: "",
              flaccWajah: 0,
              flaccKaki: 0,
              flaccAktifitas: 0,
              flaccMenangis: 0,
              flaccBersuara: 0,
              flaccTotal: 0,
              skalaTriase: 0)),
      cpptPasien: const [],
      status: ReportStatus.initial,
      intervensiResponse: const [],
      reportTriase: ReportTriaseResponseModel(
          pemeriksaanFisik: PemeriksaanFisikModel(
              mata: "",
              tht: "",
              mulut: "",
              gigi: "",
              thyroid: "",
              leherlain: "",
              dindingDada: "",
              suaraJantung: "",
              suaraParu: "",
              dindingParu: "",
              hati: "",
              lien: "",
              persitaltik: "",
              abdomenLain: "",
              kulit: "",
              ginjal: "",
              genetalia: "",
              superior: "",
              inferior: ""),
          pasien: PasienTriase(
              nik: "", id: "", firstname: "", jenisKelamin: "", tglLahir: ""),
          skalaFlacc: SkalaFlacc(
              wajah: 0, kaki: 0, aktivitas: 0, menangis: 0, bersuara: 0),
          imageLokais: ImageLokalis(image: ""),
          diagnosaModel: DiagnosaModel(
              diagnosaPrimer: "",
              diagnosaSekunder1: "",
              diagnosaSekunder2: "",
              diagnosaSekunder3: "",
              diagnosaSekunder4: "",
              diagnosaSekunder5: "",
              diagnosaSekunder6: ""),
          tandaVital: TandaVital(
              jalanNapas: "",
              td: "",
              pernafasan: "",
              nadi: "",
              spo2: "",
              e: "",
              v: "",
              m: "",
              cahaya: "",
              suhu: "",
              akral: "",
              pupilKanan: "",
              pupilKiri: ""),
          soapPerawat: SoapPerawatModel(
              insertDttm: "",
              updDttm: "",
              keteranganPerson: "",
              insertUserId: "",
              insertPc: "",
              tglMasuk: "",
              kdBagian: "",
              noreg: "",
              pelayanan: "",
              info: "",
              infoDetail: "",
              caraMasuk: "",
              caraMasukDetail: "",
              asalMasuk: "",
              asalMasukDetail: "",
              td: "",
              bb: "",
              tb: "",
              rwtPenyakit: "",
              rwtObat: "",
              fungsional: "",
              rj1: "",
              rj2: "",
              hasilRj: "",
              rjTind: "",
              dekubitus1: "",
              dekubitus2: "",
              dekubitus3: "",
              dekubitus4: "",
              dekubitusAnak: "",
              kehamilan: "",
              gravida: "",
              para: "",
              abortus: "",
              hpht: "",
              ttp: "",
              leopol1: "",
              leopol2: "",
              leopol3: "",
              leopol4: "",
              djj: "",
              vt: "",
              nyeri: 0,
              frekuensiNyeri: "",
              lamaNyeri: "",
              menjalar: "",
              menjalarDetail: "",
              kualitasNyeri: "",
              pemicu: "",
              pengurang: "",
              pulang1: "",
              pulang1Detail: "",
              pulang2: "",
              pulang2Detail: "",
              pulang3: "",
              pulang3Detail: "",
              keadaanUmum: "",
              kesadaran: "",
              kesadaranDetail: ""),
          nyeri: Nyeri(
              nyeri: 0,
              nyeriP: "",
              nyeriQ: "",
              nyeriR: "",
              nyeriS: "",
              nyeriT: "")),
      reportRawatInapResponse: null,
      reportRingkasanPulang: null);

  ReportState copyWith(
      {ReportStatus? status,
      ReportPengkajianAwalPasienRawatInapResponseModel? reportRawatInapResponse,
      ReportTriaseResponseModel? reportTriase,
      ReportRingkasanPulangResponseModel? reportRingkasanPulang,
      List<IntervensiPasienResponseModel>? intervensiResponse,
      List<ResponseCpptPasien>? cpptPasien,
      ReportPengkajianRawatInapPerawat? perawat,
      ReportPengkajianAwalRawatInapModel? reportPengkajianAwalMedis}) {
    return ReportState(
        perawat: perawat ?? this.perawat,
        reportPengkajianAwalMedis:
            reportPengkajianAwalMedis ?? this.reportPengkajianAwalMedis,
        cpptPasien: cpptPasien ?? this.cpptPasien,
        status: status ?? this.status,
        intervensiResponse: intervensiResponse ?? this.intervensiResponse,
        reportRawatInapResponse:
            reportRawatInapResponse ?? reportRawatInapResponse,
        reportTriase: reportTriase ?? this.reportTriase,
        reportRingkasanPulang:
            reportRingkasanPulang ?? this.reportRingkasanPulang);
  }

  @override
  List<Object?> get props => [
        cpptPasien,
        status,
        reportPengkajianAwalMedis,
        reportTriase,
        reportRingkasanPulang,
        reportRawatInapResponse,
        intervensiResponse
      ];
}
