// ignore_for_file: public_member_api_docs, sort_constructors_first
part of 'pengkajian_kebidanan_awal_kebidanan_bloc.dart';

enum PengkajianKebidananAwalKebidananStatus {
  initial,
  loading,
  loaded,
  error,
}

class PengkajianKebidananAwalKebidananState extends Equatable {
  final PengkajianKebidananAwalKebidananStatus status;
  final ReportPengkajianKebidanan report;

  const PengkajianKebidananAwalKebidananState({
    required this.status,
    required this.report,
  });

  @override
  List<Object?> get props => [status, report];

  static PengkajianKebidananAwalKebidananState initial() =>
      PengkajianKebidananAwalKebidananState(
          report: ReportPengkajianKebidanan(
            user: User(id: "", nama: "", jenisKelamin: "", tglLahir: ""),
            karu: User(id: "", nama: "", jenisKelamin: "", tglLahir: ""),
            penyakitKeluarga: [],
            diagnosa: [],
            fungsional: Fungsional(
                insertDttm: "",
                updDttm: "",
                device: "",
                userId: "",
                kdBagian: "",
                noreg: "",
                f1: "",
                f2: "",
                f3: "",
                f4: "",
                f5: "",
                f6: "",
                f7: "",
                f8: "",
                f9: "",
                f10: "",
                nilai: 0),
            nutrisi: Nutrisi(
                insertDttm: "",
                updDttm: "",
                device: "",
                userId: "",
                kdBagian: "",
                noreg: "",
                n1: "",
                n2: "",
                nilai: 0),
            fisik: Fisik(
                insertDttm: "",
                updDttm: "",
                device: "",
                userId: "",
                kategori: "",
                person: "",
                pelayanan: "",
                kdBagian: "",
                noreg: "",
                kepala: "",
                mata: "",
                telinga: "",
                leherDahBahu: "",
                mulut: "",
                mucosaMulut: "",
                gigi: "",
                hidung: "",
                tenggorokan: "",
                payudara: "",
                abdomen: "",
                nutrisiDanHidrasi: ""),
            pengobatanDirumah: [],
            kehamilan: [],
            vitalSign: VitalSign(
                tekananDarah: "",
                pernapasan: "",
                suhu: "",
                nadi: "",
                ddj: "",
                beratBadan: "",
                tinggiBadan: "",
                gcsE: "",
                gcsV: "",
                gcsM: "",
                tfu: ""),
            pengkajian: Pengkajian(
                kehamilanHis: "",
                kehamilanLendir: "",
                keluhanMenyertai: "",
                aktivitas: "",
                ekonomi: "",
                eliminasiBab: "",
                eliminasiBak: "",
                haidTerakhir: "",
                hamilMuda: "",
                hamilTua: "",
                hpl: "",
                istirahat: "",
                nilaiKepercayaan: "",
                pemeriksaaanDalam: "",
                spiritual: "",
                tbj: "",
                tfu: "",
                usiaKehamilan: "",
                bahasaSehari: "",
                caraBelajar: "",
                eliminasi: "",
                haid: "",
                hambatanBahasa: "",
                hambatanSosial: "",
                hamil: "",
                inspekuloP: "",
                inspekuloV: "",
                integumen: "",
                kardiovaskuler: "",
                kenyamanan: "",
                kepercayaan: "",
                mobilisasi: "",
                papsSmer: "",
                pencernaan: "",
                perfusiPerifer: "",
                presepsiSakit: "",
                proteksi: "",
                respiratori: "",
                responseEmosi: "",
                secebral: "",
                sistemBerpakaian: "",
                sistemMakan: "",
                sistemMandi: "",
                sistemPendarahan: "",
                spikologis: "",
                thermoregulasi: "",
                tglMasuk: "",
                tglKeluar: "",
                pelayanan: "",
                kdBagian: "",
                noreg: "",
                keluhanUtama: "",
                rwtPenyakit: "",
                penyakitDahulu: "",
                menstruasi: "",
                siklusHaid: "",
                rwtPernikahan: "",
                alergi: "",
                gravida: "",
                para: "",
                abortus: "",
                hpht: "",
                tpp: "",
                leopold1: "",
                leopold2: "",
                leopold3: "",
                leopold4: ""),
          ),
          status: PengkajianKebidananAwalKebidananStatus.initial);

  PengkajianKebidananAwalKebidananState copyWith({
    PengkajianKebidananAwalKebidananStatus? status,
    ReportPengkajianKebidanan? report,
  }) {
    return PengkajianKebidananAwalKebidananState(
      status: status ?? this.status,
      report: report ?? this.report,
    );
  }
}
