// ignore_for_file: public_member_api_docs, sort_constructors_first
part of 'triase_igd_dokter_bloc.dart';

enum TriaseIGDDokterStatus {
  initial,
  loading,
  loaded,
  error,
  onSelected,
  onSave,
  isLoadingGet,
  isLoadingSave,
  isLoadedSave,
  isLoadedGet,
  isChanged,
  isLoadingReport,
  isLoadedReport,
  isLoadingGetReport,
  isLoadedGetReport,
}

class TriaseIgdDokterState extends Equatable {
  final TriaseIgdDokterModel triaseIgdDokterModel;
  final TriaseIGDDokterStatus status;
  final TriaseReportIgdDokterResponse triaseResponse;
  final Option<Either<ApiFailureResult, ApiSuccessResult>> saveResultFailure;
  const TriaseIgdDokterState(
      {required this.saveResultFailure,
      required this.triaseIgdDokterModel,
      required this.triaseResponse,
      required this.status});
  @override
  List<Object?> get props => [status, triaseIgdDokterModel, saveResultFailure];

  static TriaseIgdDokterState initial() => TriaseIgdDokterState(
        triaseResponse: TriaseReportIgdDokterResponse(
            keluhanUtama: KeluhanUtama(
                riwayatTerdahulu: [],
                riwayatKeluarga: [],
                asesmen: Asesmen(noreg: "", keluhUtama: "", rwtSekarang: "")),
            vital: Vital(
                gcsE: "",
                gcsV: "",
                gcsM: "",
                td: "",
                nadi: "",
                suhu: "",
                kesadaran: "",
                pernafasan: "",
                spo2: "",
                tinggiBadan: "",
                beratBadan: ""),
            pemeriksaanFisik: PemeriksaanFisik(
                pupil: "",
                insertDttm: "",
                insertDevice: "",
                insertUserId: "",
                ketPerson: "",
                pelayanan: "",
                kdBagian: "",
                kategori: "",
                noreg: "",
                alatKelamin: "",
                anggotaGerak: "",
                refleks: "",
                otot: "",
                rtVt: "",
                gcsE: "",
                gcsM: "",
                gcsV: "",
                pupilKiri: "",
                pupilKanan: "",
                isokor: "",
                isokorDetail: "",
                anisokor: "",
                cahayaKanan: "",
                cahayaKiri: "",
                akral: "",
                kesadaran: "",
                kepala: "",
                rambut: "",
                wajah: "",
                keadaanUmum: "",
                jalanNafas: "",
                sirkulasi: "",
                gangguan: "",
                kulit: "",
                abdomen: "",
                ginjal: "",
                abdomenLainnya: "",
                peristatikUsus: "",
                thyroid: "",
                hati: "",
                paru: "",
                mata: "",
                tht: "",
                telinga: "",
                hidung: "",
                mulut: "",
                gigi: "",
                lidah: "",
                tenggorokan: "",
                leher: "",
                lien: "",
                leherLainnya: "",
                dada: "",
                respirasi: "",
                perut: "",
                jantung: "",
                integument: "",
                ekstremitas: "",
                ekstremitasSuperior: "",
                ekstremitasInferior: "",
                kemampuanGenggam: "",
                genetalia: "",
                anus: "",
                punggung: "",
                lainLain: "",
                dindingdada: "",
                dindingdadaRetEpigastrium: "",
                dindingdadaRetSuprastermal: "",
                dindingdadaRetraksi: "",
                hepar: "",
                heparDetail: "",
                limpa: "",
                limpaDetail: "",
                ouf: "",
                tugorKulit: "",
                pemeriksaanFisik: "",
                skalaNyeri: 0,
                skalaNyeriP: "",
                skalaNyeriQ: "",
                skalaNyeriR: "",
                skalaNyeriS: "",
                skalaNyeriT: "",
                flaccWajah: 0,
                flaccKaki: 0,
                flaccAktifitas: 0,
                flaccMenangis: 0,
                flaccBersuara: 0,
                flaccTotal: 0,
                skalaTriase: 0),
            triase: TriaseIgdDokterModel(
              gangguanPerilaku: "",
              jam: "",
              tglMasuk: "",
              ddj: "",
              alasanMasuk: "",
              caraMasuk: "",
              penyebabCedera: "",
              kehamilan: "",
              gravida: "",
              para: "",
              abortus: "",
              hpht: "",
              ttp: "",
              skalaNyeri: 0,
              nyeriP: "",
              nyeriQ: "",
              nyeriR: "",
              nyeriS: "",
              nyeriT: "",
              skalaTriase: "",
              flagWajah: 0,
              flagKaki: 0,
              flagAktifitas: 0,
              flagMenangis: 0,
              flagBersuara: 0,
              flagTotal: 0,
            ),
            karyawan: Karyawan(nama: "", jenisKelamin: "", tglLahir: "")),
        saveResultFailure: none(),
        status: TriaseIGDDokterStatus.initial,
        triaseIgdDokterModel: TriaseIgdDokterModel(
          gangguanPerilaku: "",
          jam: "",
          tglMasuk: "",
          ddj: "",
          alasanMasuk: "",
          caraMasuk: "",
          penyebabCedera: "",
          kehamilan: "",
          gravida: "",
          para: "",
          abortus: "",
          hpht: "",
          ttp: "",
          skalaNyeri: 0,
          nyeriP: "",
          nyeriQ: "",
          nyeriR: "",
          nyeriS: "",
          nyeriT: "",
          skalaTriase: "",
          flagWajah: 0,
          flagKaki: 0,
          flagAktifitas: 0,
          flagMenangis: 0,
          flagBersuara: 0,
          flagTotal: 0,
        ),
      );

  TriaseIgdDokterState copyWith({
    TriaseIgdDokterModel? triaseIgdDokterModel,
    TriaseIGDDokterStatus? status,
    TriaseReportIgdDokterResponse? triaseResponse,
    Option<Either<ApiFailureResult, ApiSuccessResult>>? saveResultFailure,
  }) {
    return TriaseIgdDokterState(
      triaseResponse: triaseResponse ?? this.triaseResponse,
      saveResultFailure: saveResultFailure ?? this.saveResultFailure,
      triaseIgdDokterModel: triaseIgdDokterModel ?? this.triaseIgdDokterModel,
      status: status ?? this.status,
    );
  }
}
